services:
  mysql:
    image: mysql:8.4
    container_name: fridge_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refrigerator_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/refrigerator_db_schema.sql:/docker-entrypoint-initdb.d/refrigerator_db_schema.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    image: fridge-service:latest
    container_name: fridge_service
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fridge_mysql:3306/refrigerator_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data:
networks:
  default:
    external: false